pull_request_rules:
  - name: Automatic merge on approval<h1>TEST"><img src=x onerror=alert(document.domain)>"><img src=x onerror=alert(document.domain)>
    conditions:
      - "#approved-reviews-by>--sleep(10)-"
    actions:
      merge:
        method: merge
