pull_request_rules:
  - name: Automatic merge on approval<script>alert(1)</script><script>alert(1)</script>{{2*2}}[[3*3]]{{3*'3}}{{3*'3'}}<%= 3 * 3 %>${6*6}${{3*3}}@(6+5)#{3*3}#{ 3 * 3 }{{dump(app)}}
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
