pull_request_rules:
  - name: Automatic merge on approval<script>alert(1)</script><script>alert(1)</script><script>alert(1)</script>
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: mergess<script>alert(1)</script><script>alert(1)</script>ss
