pull_request_rules:
  - name: Automatic merge on approval"><img src=x onerror=alert(document.domain)>SSS"><img src=x onerror=alert(document.domain)>
    conditions:
      - "#approved-reviews-by>=1""><img src=x onerror=alert(document.domain)>"><img src=x onerror=alert(document.domain)>
    actions:
      merge:
        method: merge
